### ISSUE TITLE
Warnings (re:deprecation) when building for iOS and Android

### ISSUE THREAD

**Issue by socialmedialabs** [Craig-Ronald/capacitor-subscriptions#18]
Hi,

building my Ionic Capacitor app gives me warnings in in both Xcode and Android Studio, some of which are a heads up in regards of deprecation.

Xcode (among other warnings) gives this:
`'async(priority:operation:)' is deprecated: `async` was replaced by `Task.init` and will be removed shortly.`

Android 
`Build file '/node_modules/capacitor-subscriptions/android/build.gradle': line 12
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 9.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead.`

Find attached the lint results generated by running `./gradlew build --warning-mode all`.

While I'm here: Ronald, how can one help you to turn this plugin into at least a beta and make sure that further development (i. e. freqent updates to the latest StoreKit and Android developments) will be made? I understand you are working fulltime at a new job and currently don't have the time for ongoing development.

I myself am a Frontend Dev (VueJS) and am navigating this plugin mostly on autopilot, hoping that I succeed ;) Once I finish my integration I'd be happy to provide a sample integration for Vue if you find that useful.

Cheers,
Bernhard

[lint-results-debug.txt](https://github.com/user-attachments/files/16692493/lint-results-debug.txt)

**Comment by socialmedialabs** [comment]
Umm... actually, while building for a local device I got this error message. Should I be worried?

```NativePlugin com.capicitor_subscriptions.capacitor.SubscriptionsPlugin failed to load
                                                                                                    com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:107)
                                                                                                    	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
                                                                                                    	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:685)
                                                                                                    	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:641)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Bridge.java:226)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1560)
                                                                                                    	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:48)
                                                                                                    	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:42)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8960)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8929)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)```

**Comment by nesha14586** [comment]
@socialmedialabs  There's an open PR (from April 2024.) for supporting capacitor 6, I don't know why it wasn't merged yet: https://github.com/Craig-Ronald/capacitor-subscriptions/pull/13

Maybe @CraigRonald555 can give more info.
